robot:
  kinematics_solver: pr2_arm_kinematics/PR2ArmKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 5
  kinematics_solver_attempts: 3
base:
  kinematics_solver: pr2_arm_kinematics/PR2ArmKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 5
  kinematics_solver_attempts: 3
arm:
  kinematics_solver: constrained_ik/ConstrainedIKPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 5
  kinematics_solver_attempts: 3